import { db, handleFirestoreError, OperationType } from './firebase';
import LZString from 'lz-string';
import { clearCache } from './cache';
import {
  collection,
  doc,
  getDocs,
  getDoc,
  addDoc,
  updateDoc,
  deleteDoc,
  setDoc,
  query,
  where,
  orderBy,
  serverTimestamp,
  Timestamp,
} from 'firebase/firestore';

const decompressHtml = (html: string | null | undefined) => {
  if (!html) return html;
  if (html.startsWith('LZ16:')) {
    try {
      const decompressed = LZString.decompressFromUTF16(html.substring(5));
      if (decompressed) return decompressed;
    } catch (e) {
      console.warn("Error decompressing HTML:", e);
    }
    // If decompression fails, do NOT return the raw mojibake string.
    // Return empty string so it doesn't pollute the UI. The data is corrupted.
    return '';
  }
  return html; // Already decompressed or never compressed
};

// We no longer compress HTML because Firebase Firestore corrupts UTF-16 
// unpaired surrogates generated by LZString.compressToUTF16.
// Instead we rely entirely on document chunking.
const compressHtml = (html: string | null | undefined) => {
  return html;
};

// ============ CATEGORIES ============
export const getCategories = async () => {
  try {
    const q = query(collection(db, 'categories'));
    const snap = await getDocs(q);
    const cats = snap.docs.map(d => ({ id: d.id, ...d.data() as any }));
    return cats.sort((a, b) => (a.display_order || 0) - (b.display_order || 0));
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, 'categories');
    return [];
  }
};

export const addCategory = async (name: string, displayOrder: number) => {
  try {
    const res = await addDoc(collection(db, 'categories'), {
      name,
      display_order: displayOrder,
      created_at: serverTimestamp(),
    });
    clearCache();
    return res;
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, 'categories');
    throw error;
  }
};

export const updateCategory = async (id: string, data: Record<string, any>) => {
  await updateDoc(doc(db, 'categories', id), data);
  clearCache();
};

export const deleteCategory = async (id: string) => {
  await deleteDoc(doc(db, 'categories', id));
  clearCache();
};

// ============ CATEGORY LINKS ============
export const getCategoryLinks = async () => {
  const q = query(collection(db, 'category_links'));
  const snap = await getDocs(q);
  const links = snap.docs.map(d => {
    const data = d.data() as any;
    let ts = data.link_timestamp;
    if (typeof ts === 'undefined') {
      ts = data.created_at?.toMillis ? data.created_at.toMillis() : 0;
    }
    // If the old item had display_order, subtract it so older items keep rough relative order (smaller display_order = higher priority natively, so we give them a slight boost)
    if (typeof ts === 'undefined') ts = 0;
    return { id: d.id, ...data, link_timestamp: ts };
  });
  // Sort descending by timestamp (newest or intentionally bumped to top)
  return links.sort((a, b) => b.link_timestamp - a.link_timestamp);
};

export const addCategoryLink = async (data: {
  category_id: string;
  title: string;
  url: string;
  link_timestamp?: number;
  is_new: boolean;
  last_date_text: string | null;
}) => {
  const ts = typeof data.link_timestamp !== 'undefined' ? data.link_timestamp : Date.now();
  const res = await addDoc(collection(db, 'category_links'), {
    ...data,
    link_timestamp: ts,
    created_at: serverTimestamp(),
  });
  clearCache();
  return res;
};

export const updateCategoryLink = async (id: string, data: Record<string, any>) => {
  await updateDoc(doc(db, 'category_links', id), data);
  clearCache();
};

export const deleteCategoryLink = async (id: string) => {
  await deleteDoc(doc(db, 'category_links', id));
  clearCache();
};

export const deleteCategoryLinksByCategoryId = async (categoryId: string) => {
  const q = query(collection(db, 'category_links'), where('category_id', '==', categoryId));
  const snap = await getDocs(q);
  const deletes = snap.docs.map(d => deleteDoc(d.ref));
  await Promise.all(deletes);
  clearCache();
};

// ============ TABLET ITEMS ============
export const getTabletItems = async () => {
  const q = query(collection(db, 'tablet_items'));
  const snap = await getDocs(q);
  const items = snap.docs.map(d => ({ id: d.id, ...d.data() as any }));
  return items.sort((a, b) => (a.display_order || 0) - (b.display_order || 0));
};

export const addTabletItem = async (title: string, subtitle: string, url: string, displayOrder: number) => {
  const res = await addDoc(collection(db, 'tablet_items'), {
    title,
    subtitle,
    url,
    display_order: displayOrder,
    created_at: serverTimestamp(),
  });
  clearCache();
  return res;
};

export const updateTabletItem = async (id: string, data: Record<string, any>) => {
  await updateDoc(doc(db, 'tablet_items', id), data);
  clearCache();
};

export const deleteTabletItem = async (id: string) => {
  await deleteDoc(doc(db, 'tablet_items', id));
  clearCache();
};

// ============ POSTS ============
export const loadChunksForPost = async (id: string, postData: any) => {
  if (postData.is_chunked) {
    try {
      const chunksSnap = await getDocs(query(collection(db, `posts/${id}/chunks`), orderBy('index')));
      let full_html = '';
      let full_html_hi = '';
      chunksSnap.docs.forEach(doc => {
        const data = doc.data();
        if (data.html) full_html += data.html;
        if (data.html_hi) full_html_hi += data.html_hi;
      });
      postData.tables_html = full_html ? decompressHtml(full_html) : '';
      postData.tables_html_hi = full_html_hi ? decompressHtml(full_html_hi) : '';
    } catch(e) {
      console.error("Error loading chunks for post", id, e);
      postData.tables_html = '';
      postData.tables_html_hi = '';
    }
  } else {
    postData.tables_html = decompressHtml(postData.tables_html);
    postData.tables_html_hi = decompressHtml(postData.tables_html_hi);
  }
};

export const getPosts = async () => {
  try {
    const q = query(collection(db, 'posts'));
    const snap = await getDocs(q);
    const posts = snap.docs.map(d => {
      const data = d.data() as Record<string, any>;
      return {
        id: d.id,
        ...data,
        tables_html: decompressHtml(data.tables_html),
        tables_html_hi: decompressHtml(data.tables_html_hi),
        created_at: data.created_at?.toDate?.()?.toISOString?.() || data.created_at || '',
        updated_at: data.updated_at?.toDate?.()?.toISOString?.() || data.updated_at || '',
      } as Record<string, any>;
    });
    
    // We explicitly DO NOT load chunks here to prevent OOM errors on Vercel SSG process
    // when processing thousands of large posts. Chunks are loaded individually by loaders.

    return posts.sort((a, b) => {
      const dateA = a.post_timestamp || new Date(a.updated_at || a.created_at || 0).getTime();
      const dateB = b.post_timestamp || new Date(b.updated_at || b.created_at || 0).getTime();
      return dateB - dateA;
    });
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, 'posts');
    return [];
  }
};

export const getPostBySlug = async (slug: string): Promise<Record<string, any> | null> => {
  try {
    const q = query(collection(db, 'posts'), where('slug', '==', slug));
    const snap = await getDocs(q);
    if (!snap.empty) {
      const d = snap.docs[0];
      const data = { id: d.id, ...d.data() };
      await loadChunksForPost(d.id, data);
      return data;
    }
    const docRef = doc(db, 'posts', slug);
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      const data = { id: docSnap.id, ...docSnap.data() };
      await loadChunksForPost(docSnap.id, data);
      return data;
    }
    return null;
  } catch (error) {
    handleFirestoreError(error, OperationType.GET, `posts/${slug}`);
    return null;
  }
};

export const getPostById = async (id: string): Promise<Record<string, any> | null> => {
  const docRef = doc(db, 'posts', id);
  const docSnap = await getDoc(docRef);
  if (docSnap.exists()) {
    const data = { id: docSnap.id, ...docSnap.data() };
    await loadChunksForPost(docSnap.id, data);
    return data;
  }
  return null;
};

const CHUNK_SIZE = 200000;

export const createPost = async (data: Record<string, any>) => {
  const postData = { ...data };
  
  const html = (postData.tables_html ? compressHtml(postData.tables_html) : '') as string;
  const html_hi = (postData.tables_html_hi ? compressHtml(postData.tables_html_hi) : '') as string;
  
  const isChunked = (html.length + html_hi.length) > CHUNK_SIZE;
  
  if (isChunked) {
    postData.tables_html = '';
    postData.tables_html_hi = '';
    postData.is_chunked = true;
  } else {
    postData.tables_html = html;
    postData.tables_html_hi = html_hi;
    postData.is_chunked = false;
  }

  const docRef = await addDoc(collection(db, 'posts'), {
    ...postData,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp(),
  });
  
  if (isChunked) {
    const maxLen = Math.max(html.length, html_hi.length);
    let index = 0;
    for (let i = 0; i < maxLen; i += CHUNK_SIZE) {
      await setDoc(doc(db, `posts/${docRef.id}/chunks`, index.toString()), {
        index,
        html: html.substring(i, i + CHUNK_SIZE),
        html_hi: html_hi.substring(i, i + CHUNK_SIZE),
      });
      index++;
    }
  }

  clearCache();
  return { id: docRef.id, ...data };
};

export const updatePost = async (id: string, data: Record<string, any>) => {
  const postData = { ...data };
  
  const html: string | undefined = postData.tables_html !== undefined ? (compressHtml(postData.tables_html) as string) || '' : undefined;
  const html_hi: string | undefined = postData.tables_html_hi !== undefined ? (compressHtml(postData.tables_html_hi) as string) || '' : undefined;
  
  const lenHtml = html ? html.length : 0;
  const lenHtmlHi = html_hi ? html_hi.length : 0;
  const isChunked = (lenHtml + lenHtmlHi) > CHUNK_SIZE;
  
  if (isChunked) {
    postData.tables_html = '';
    postData.tables_html_hi = '';
    postData.is_chunked = true;
  } else {
    if (html !== undefined) postData.tables_html = html;
    if (html_hi !== undefined) postData.tables_html_hi = html_hi;
    postData.is_chunked = false;
  }

  // Clear old chunks in any case just to be safe
  try {
    const deletePromises = [];
    for (let i = 0; i < 100; i++) {
      deletePromises.push(deleteDoc(doc(db, `posts/${id}/chunks`, i.toString())));
    }
    await Promise.all(deletePromises);
  } catch(e) {
    console.warn("Could not delete post chunks (likely insufficient permissions or they do not exist):", e);
  }

  await updateDoc(doc(db, 'posts', id), {
    ...postData,
    updated_at: serverTimestamp(),
  });
  
  if (isChunked && html !== undefined && html_hi !== undefined) {
    const maxLen = Math.max(html.length, html_hi.length);
    let index = 0;
    for (let i = 0; i < maxLen; i += CHUNK_SIZE) {
      await setDoc(doc(db, `posts/${id}/chunks`, index.toString()), {
        index,
        html: html.substring(i, i + CHUNK_SIZE),
        html_hi: html_hi.substring(i, i + CHUNK_SIZE),
      });
      index++;
    }
  }

  clearCache();
};

export const deletePost = async (id: string) => {
  try {
    try {
      const deletePromises = [];
      for (let i = 0; i < 100; i++) {
        deletePromises.push(deleteDoc(doc(db, `posts/${id}/chunks`, i.toString())));
      }
      await Promise.all(deletePromises);
    } catch(e) {
      console.warn("Could not delete post chunks (likely insufficient permissions or they do not exist):", e);
    }
    await deleteDoc(doc(db, 'posts', id));
    clearCache();
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `posts/${id}`);
  }
};

// ============ SITE SETTINGS ============
export const getSiteSettings = async () => {
  const snap = await getDocs(collection(db, 'site_settings'));
  const settings: Record<string, any> = {};
  snap.docs.forEach(d => {
    const data = d.data();
    settings[data.key] = { id: d.id, key: data.key, value: data.value };
  });
  return settings;
};

export const getSiteSettingsFlat = async () => {
  const snap = await getDocs(collection(db, 'site_settings'));
  const settings: Record<string, string> = {};
  snap.docs.forEach(d => {
    const data = d.data();
    settings[data.key] = data.value;
  });
  return settings;
};

export const updateSiteSetting = async (key: string, value: string, existingId?: string) => {
  if (existingId) {
    await updateDoc(doc(db, 'site_settings', existingId), { value, updated_at: serverTimestamp() });
  } else {
    await addDoc(collection(db, 'site_settings'), { key, value, updated_at: serverTimestamp() });
  }
  clearCache();
};

export const getSiteLastUpdated = async (): Promise<number> => {
  const docRef = doc(db, 'site_settings', 'last_updated');
  const docSnap = await getDoc(docRef);
  if (docSnap.exists()) {
    return docSnap.data().timestamp || 0;
  }
  return 0;
};

export const updateSiteLastUpdated = async () => {
  const docRef = doc(db, 'site_settings', 'last_updated');
  await setDoc(docRef, { timestamp: Date.now() }, { merge: true });
};

// Removed realtime listeners
