import { db, handleFirestoreError, OperationType } from './firebase';
import LZString from 'lz-string';
import { clearCache } from './cache';
import {
  collection,
  doc,
  getDocs,
  getDoc,
  addDoc,
  updateDoc,
  deleteDoc,
  setDoc,
  query,
  where,
  orderBy,
  serverTimestamp,
  Timestamp,
  writeBatch,
} from 'firebase/firestore';

const decompressHtml = (html: string | null | undefined) => {
  if (!html) return html;
  if (html.startsWith('LZ16:')) {
    try {
      const decompressed = LZString.decompressFromUTF16(html.substring(5));
      if (decompressed) return decompressed;
    } catch (e) {
      console.warn("Error decompressing HTML:", e);
    }
    // If decompression fails, do NOT return the raw mojibake string.
    // Return empty string so it doesn't pollute the UI. The data is corrupted.
    return '';
  }
  return html; // Already decompressed or never compressed
};

// We no longer compress HTML because Firebase Firestore corrupts UTF-16 
// unpaired surrogates generated by LZString.compressToUTF16.
// Instead we rely entirely on document chunking.
const compressHtml = (html: string | null | undefined) => {
  return html;
};

// Local in-memory and localStorage cache for saving hundreds/thousands of Firestore reads
const getLocalAdminCache = <T>(key: string): T | null => {
  try {
    const item = localStorage.getItem(`admin_db_cache_${key}`);
    if (!item) return null;
    const { data } = JSON.parse(item);
    // Cache has NO auto-expiration now. It is 100% persistent until the user clicks manual Refresh.
    return data as T;
  } catch {
    return null;
  }
};

const setLocalAdminCache = (key: string, data: any) => {
  try {
    localStorage.setItem(`admin_db_cache_${key}`, JSON.stringify({ data, timestamp: Date.now() }));
  } catch {
    // ignore quotas/storage errors safely
  }
};

export const clearLocalAdminCache = () => {
  try {
    ['categories', 'category_links', 'tablet_items', 'posts', 'site_settings'].forEach(key => {
      localStorage.removeItem(`admin_db_cache_${key}`);
    });
  } catch {
    // ignore
  }
};

// ============ CATEGORIES ============
export const getCategories = async () => {
  const cached = getLocalAdminCache<any[]>('categories');
  if (cached && cached.length > 0) {
    return cached;
  }
  try {
    const q = query(collection(db, 'categories'));
    const snap = await getDocs(q);
    const cats = snap.docs.map(d => ({ id: d.id, ...d.data() as any }));
    const sorted = cats.sort((a, b) => (a.display_order || 0) - (b.display_order || 0));
    setLocalAdminCache('categories', sorted);
    return sorted;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, 'categories');
    return [];
  }
};

export const addCategory = async (name: string, displayOrder: number) => {
  try {
    const res = await addDoc(collection(db, 'categories'), {
      name,
      display_order: displayOrder,
      created_at: serverTimestamp(),
    });
    const cached = getLocalAdminCache<any[]>('categories');
    if (cached) {
      const newCat = { id: res.id, name, display_order: displayOrder };
      const nextCats = [...cached, newCat].sort((a, b) => (a.display_order || 0) - (b.display_order || 0));
      setLocalAdminCache('categories', nextCats);
    }
    clearCache();
    return res;
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, 'categories');
    throw error;
  }
};

export const updateCategory = async (id: string, data: Record<string, any>) => {
  if (!id || typeof id !== 'string' || id.trim() === '') {
    console.warn('[Firebase] updateCategory skipped: invalid or empty document ID');
    return;
  }
  await setDoc(doc(db, 'categories', id), data, { merge: true });
  const cached = getLocalAdminCache<any[]>('categories');
  if (cached) {
    const nextCats = cached.map(cat => cat.id === id ? { ...cat, ...data } : cat)
      .sort((a, b) => (a.display_order || 0) - (b.display_order || 0));
    setLocalAdminCache('categories', nextCats);
  }
  clearCache();
};

export const deleteCategory = async (id: string) => {
  if (!id || typeof id !== 'string' || id.trim() === '') {
    console.warn('[Firebase] deleteCategory skipped: invalid or empty document ID');
    return;
  }
  await deleteDoc(doc(db, 'categories', id));
  const cached = getLocalAdminCache<any[]>('categories');
  if (cached) {
    setLocalAdminCache('categories', cached.filter(cat => cat.id !== id));
  }
  clearCache();
};

// ============ CATEGORY LINKS ============
export const getCategoryLinks = async () => {
  const cached = getLocalAdminCache<any[]>('category_links');
  if (cached && cached.length > 0) {
    return cached;
  }
  try {
    const q = query(collection(db, 'category_links'));
    const snap = await getDocs(q);
    const links = snap.docs.map(d => {
      const data = d.data() as any;
      let ts = data.link_timestamp;
      if (typeof ts === 'undefined') {
        ts = data.created_at?.toMillis ? data.created_at.toMillis() : 0;
      }
      if (typeof ts === 'undefined') ts = 0;
      return { id: d.id, ...data, link_timestamp: ts };
    });
    const sorted = links.sort((a, b) => b.link_timestamp - a.link_timestamp);
    setLocalAdminCache('category_links', sorted);
    return sorted;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, 'category_links');
    return [];
  }
};

export const addCategoryLink = async (data: {
  category_id: string;
  title: string;
  url: string;
  link_timestamp?: number;
  post_date?: string;
  is_new: boolean;
  last_date_text: string | null;
}) => {
  const ts = typeof data.link_timestamp !== 'undefined' ? data.link_timestamp : Date.now();
  const res = await addDoc(collection(db, 'category_links'), {
    ...data,
    link_timestamp: ts,
    created_at: serverTimestamp(),
  });
  const cached = getLocalAdminCache<any[]>('category_links');
  if (cached) {
    const newLink = { id: res.id, ...data, link_timestamp: ts };
    const nextLinks = [newLink, ...cached].sort((a, b) => b.link_timestamp - a.link_timestamp);
    setLocalAdminCache('category_links', nextLinks);
  }
  clearCache();
  return res;
};

export const updateCategoryLink = async (id: string, data: Record<string, any>) => {
  if (!id || typeof id !== 'string' || id.trim() === '') {
    console.warn('[Firebase] updateCategoryLink skipped: invalid or empty document ID');
    return;
  }
  await setDoc(doc(db, 'category_links', id), data, { merge: true });
  const cached = getLocalAdminCache<any[]>('category_links');
  if (cached) {
    const nextLinks = cached.map(link => {
      if (link.id === id) {
        const updated = { ...link, ...data };
        if (data.link_timestamp !== undefined) {
          updated.link_timestamp = data.link_timestamp;
        }
        return updated;
      }
      return link;
    }).sort((a, b) => b.link_timestamp - a.link_timestamp);
    setLocalAdminCache('category_links', nextLinks);
  }
  clearCache();
};

export const deleteCategoryLink = async (id: string) => {
  if (!id || typeof id !== 'string' || id.trim() === '') {
    console.warn('[Firebase] deleteCategoryLink skipped: invalid or empty document ID');
    return;
  }
  await deleteDoc(doc(db, 'category_links', id));
  const cached = getLocalAdminCache<any[]>('category_links');
  if (cached) {
    setLocalAdminCache('category_links', cached.filter(link => link.id !== id));
  }
  clearCache();
};

export const deleteCategoryLinksByCategoryId = async (categoryId: string) => {
  const q = query(collection(db, 'category_links'), where('category_id', '==', categoryId));
  const snap = await getDocs(q);
  const deletes = snap.docs.map(d => deleteDoc(d.ref));
  await Promise.all(deletes);
  const cached = getLocalAdminCache<any[]>('category_links');
  if (cached) {
    setLocalAdminCache('category_links', cached.filter(link => link.category_id !== categoryId));
  }
  clearCache();
};

// ============ TABLET ITEMS ============
export const getTabletItems = async () => {
  const cached = getLocalAdminCache<any[]>('tablet_items');
  if (cached && cached.length > 0) {
    return cached;
  }
  try {
    const q = query(collection(db, 'tablet_items'));
    const snap = await getDocs(q);
    const items = snap.docs.map(d => ({ id: d.id, ...d.data() as any }));
    const sorted = items.sort((a, b) => (a.display_order || 0) - (b.display_order || 0));
    setLocalAdminCache('tablet_items', sorted);
    return sorted;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, 'tablet_items');
    return [];
  }
};

export const addTabletItem = async (title: string, subtitle: string, url: string, displayOrder: number) => {
  const res = await addDoc(collection(db, 'tablet_items'), {
    title,
    subtitle,
    url,
    display_order: displayOrder,
    created_at: serverTimestamp(),
  });
  const cached = getLocalAdminCache<any[]>('tablet_items');
  if (cached) {
    const newItem = { id: res.id, title, subtitle, url, display_order: displayOrder };
    const nextItems = [...cached, newItem].sort((a, b) => (a.display_order || 0) - (b.display_order || 0));
    setLocalAdminCache('tablet_items', nextItems);
  }
  clearCache();
  return res;
};

export const updateTabletItem = async (id: string, data: Record<string, any>) => {
  if (!id || typeof id !== 'string' || id.trim() === '') {
    console.warn('[Firebase] updateTabletItem skipped: invalid or empty document ID');
    return;
  }
  await setDoc(doc(db, 'tablet_items', id), data, { merge: true });
  const cached = getLocalAdminCache<any[]>('tablet_items');
  if (cached) {
    const nextItems = cached.map(item => item.id === id ? { ...item, ...data } : item)
      .sort((a, b) => (a.display_order || 0) - (b.display_order || 0));
    setLocalAdminCache('tablet_items', nextItems);
  }
  clearCache();
};

export const deleteTabletItem = async (id: string) => {
  if (!id || typeof id !== 'string' || id.trim() === '') {
    console.warn('[Firebase] deleteTabletItem skipped: invalid or empty document ID');
    return;
  }
  await deleteDoc(doc(db, 'tablet_items', id));
  const cached = getLocalAdminCache<any[]>('tablet_items');
  if (cached) {
    setLocalAdminCache('tablet_items', cached.filter(item => item.id !== id));
  }
  clearCache();
};

// ============ POSTS ============
export const loadChunksForPost = async (id: string, postData: any) => {
  if (postData.is_chunked) {
    try {
      let full_html = '';
      let full_html_hi = '';
      const chunkCount = postData.chunk_count || 0;
      
      if (chunkCount === 0) {
        // Fallback to legacy chunks if they exist (unlikely to have permissions though)
        try {
          const chunksSnap = await getDocs(query(collection(db, `posts/${id}/chunks`), orderBy('index')));
          chunksSnap.docs.forEach(doc => {
            const data = doc.data();
            if (data.html) full_html += data.html;
            if (data.html_hi) full_html_hi += data.html_hi;
          });
        } catch(e) { /* ignore fallback errors */ }
      } else {
        const promises = [];
        for (let i = 0; i < chunkCount; i++) {
          promises.push(getDoc(doc(db, 'posts', `${id}_chunk_${i}`)));
        }
        const snaps = await Promise.all(promises);
        snaps.forEach(snap => {
          if (snap.exists()) {
            const data = snap.data();
            if (data.html) full_html += data.html;
            if (data.html_hi) full_html_hi += data.html_hi;
          }
        });
      }
      
      postData.tables_html = full_html ? decompressHtml(full_html) : '';
      postData.tables_html_hi = full_html_hi ? decompressHtml(full_html_hi) : '';
    } catch(e) {
      console.error("Error loading chunks for post", id, e);
      postData.tables_html = '';
      postData.tables_html_hi = '';
    }
  } else {
    postData.tables_html = decompressHtml(postData.tables_html);
    postData.tables_html_hi = decompressHtml(postData.tables_html_hi);
  }
};

export const getPosts = async () => {
  const cached = getLocalAdminCache<any[]>('posts');
  if (cached && cached.length > 0) {
    return cached;
  }
  try {
    const q = query(collection(db, 'posts'));
    const snap = await getDocs(q);
    const posts = snap.docs
      .map(d => {
        const data = d.data() as Record<string, any>;
        return {
          id: d.id,
          ...data,
          tables_html: decompressHtml(data.tables_html),
          tables_html_hi: decompressHtml(data.tables_html_hi),
          created_at: data.created_at?.toDate?.()?.toISOString?.() || data.created_at || '',
          updated_at: data.updated_at?.toDate?.()?.toISOString?.() || data.updated_at || '',
        } as Record<string, any>;
      })
      .filter(p => !p.id.includes('_chunk_') && p.name_of_post);
    
    // We explicitly DO NOT load chunks here to prevent OOM errors on Vercel SSG process
    const sorted = posts.sort((a, b) => {
      const dateA = a.post_timestamp || new Date(a.updated_at || a.created_at || 0).getTime();
      const dateB = b.post_timestamp || new Date(b.updated_at || b.created_at || 0).getTime();
      return dateB - dateA;
    });
    setLocalAdminCache('posts', sorted);
    return sorted;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, 'posts');
    return [];
  }
};

export const getPostBySlug = async (slug: string): Promise<Record<string, any> | null> => {
  try {
    const q = query(collection(db, 'posts'), where('slug', '==', slug));
    const snap = await getDocs(q);
    if (!snap.empty) {
      const d = snap.docs[0];
      const data = { id: d.id, ...d.data() };
      await loadChunksForPost(d.id, data);
      return data;
    }
    const docRef = doc(db, 'posts', slug);
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      const data = { id: docSnap.id, ...docSnap.data() };
      await loadChunksForPost(docSnap.id, data);
      return data;
    }
    return null;
  } catch (error) {
    handleFirestoreError(error, OperationType.GET, `posts/${slug}`);
    return null;
  }
};

export const getPostById = async (id: string): Promise<Record<string, any> | null> => {
  try {
    const docRef = doc(db, 'posts', id);
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      const data = { id: docSnap.id, ...docSnap.data() };
      await loadChunksForPost(docSnap.id, data);
      return data;
    }
    return null;
  } catch (error) {
    handleFirestoreError(error, OperationType.GET, `posts/${id}`);
    return null;
  }
};

const CHUNK_SIZE = 200000;

export const createPost = async (data: Record<string, any>) => {
  const postData = { ...data };
  
  const html = (postData.tables_html ? compressHtml(postData.tables_html) : '') as string;
  const html_hi = (postData.tables_html_hi ? compressHtml(postData.tables_html_hi) : '') as string;
  
  const isChunked = (html.length + html_hi.length) > CHUNK_SIZE;
  const chunkCount = isChunked ? Math.ceil(Math.max(html.length, html_hi.length) / CHUNK_SIZE) : 0;
  
  if (isChunked) {
    postData.tables_html = '';
    postData.tables_html_hi = '';
    postData.is_chunked = true;
    postData.chunk_count = chunkCount;
  } else {
    postData.tables_html = html;
    postData.tables_html_hi = html_hi;
    postData.is_chunked = false;
    postData.chunk_count = 0;
  }

  const docRef = await addDoc(collection(db, 'posts'), {
    ...postData,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp(),
  });
  
  if (isChunked) {
    const maxLen = Math.max(html.length, html_hi.length);
    let index = 0;
    
    // Process chunks in batches of up to 400 writes
    let currentBatch = writeBatch(db);
    let writesInBatch = 0;
    
    for (let i = 0; i < maxLen; i += CHUNK_SIZE) {
      if (writesInBatch >= 400) {
        await currentBatch.commit();
        currentBatch = writeBatch(db);
        writesInBatch = 0;
      }
      const chunkRef = doc(db, 'posts', `${docRef.id}_chunk_${index}`);
      currentBatch.set(chunkRef, {
        index,
        html: html.substring(i, i + CHUNK_SIZE),
        html_hi: html_hi.substring(i, i + CHUNK_SIZE),
      });
      writesInBatch++;
      index++;
    }
    
    if (writesInBatch > 0) {
      await currentBatch.commit();
    }
  }

  // Update posts cache
  const cached = getLocalAdminCache<any[]>('posts');
  if (cached) {
    const newPost = {
      id: docRef.id,
      ...data,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };
    const nextPosts = [newPost, ...cached].sort((a, b) => {
      const dateA = a.post_timestamp || new Date(a.updated_at || a.created_at || 0).getTime();
      const dateB = b.post_timestamp || new Date(b.updated_at || b.created_at || 0).getTime();
      return dateB - dateA;
    });
    setLocalAdminCache('posts', nextPosts);
  }

  clearCache();
  return { id: docRef.id, ...data };
};

export const updatePost = async (id: string, data: Record<string, any>) => {
  if (!id || typeof id !== 'string' || id.trim() === '') {
    console.warn('[Firebase] updatePost skipped: invalid or empty document ID');
    return;
  }
  const postData = { ...data };
  
  const html: string | undefined = postData.tables_html !== undefined ? (compressHtml(postData.tables_html) as string) || '' : undefined;
  const html_hi: string | undefined = postData.tables_html_hi !== undefined ? (compressHtml(postData.tables_html_hi) as string) || '' : undefined;
  
  const lenHtml = html ? html.length : 0;
  const lenHtmlHi = html_hi ? html_hi.length : 0;
  const isChunked = (lenHtml + lenHtmlHi) > CHUNK_SIZE;
  const newChunkCount = isChunked ? Math.ceil(Math.max(lenHtml, lenHtmlHi) / CHUNK_SIZE) : 0;
  
  if (isChunked) {
    postData.tables_html = '';
    postData.tables_html_hi = '';
    postData.is_chunked = true;
    postData.chunk_count = newChunkCount;
  } else {
    if (html !== undefined) postData.tables_html = html;
    if (html_hi !== undefined) postData.tables_html_hi = html_hi;
    postData.is_chunked = false;
    postData.chunk_count = 0;
  }

  const oldDocSnap = await getDoc(doc(db, 'posts', id));
  const oldChunkCount = oldDocSnap.exists() ? (oldDocSnap.data().chunk_count || 0) : 0;

  await setDoc(doc(db, 'posts', id), {
    ...postData,
    updated_at: serverTimestamp(),
  }, { merge: true });
  
  if (isChunked && html !== undefined && html_hi !== undefined) {
    const maxLen = Math.max(html.length, html_hi.length);
    let index = 0;
    
    // Process chunks in batches of up to 400 writes
    let currentBatch = writeBatch(db);
    let writesInBatch = 0;
    
    for (let i = 0; i < maxLen; i += CHUNK_SIZE) {
      if (writesInBatch >= 400) {
        await currentBatch.commit();
        currentBatch = writeBatch(db);
        writesInBatch = 0;
      }
      const chunkRef = doc(db, 'posts', `${id}_chunk_${index}`);
      currentBatch.set(chunkRef, {
        index,
        html: html.substring(i, i + CHUNK_SIZE),
        html_hi: html_hi.substring(i, i + CHUNK_SIZE),
      });
      writesInBatch++;
      index++;
    }
    
    if (writesInBatch > 0) {
      await currentBatch.commit();
    }
  }

  // delete older chunks extending beyond the newly written set
  if (oldChunkCount > newChunkCount) {
    let deleteBatch = writeBatch(db);
    let deletes = 0;
    for (let i = newChunkCount; i < oldChunkCount; i++) {
       deleteBatch.delete(doc(db, 'posts', `${id}_chunk_${i}`));
       deletes++;
       if (deletes >= 400) {
         await deleteBatch.commit();
         deleteBatch = writeBatch(db);
         deletes = 0;
       }
    }
    if (deletes > 0) {
        await deleteBatch.commit();
    }
  }

  // Update posts cache
  const cached = getLocalAdminCache<any[]>('posts');
  if (cached) {
    const nextPosts = cached.map(post => {
      if (post.id === id) {
        return {
          ...post,
          ...data,
          updated_at: new Date().toISOString(),
        };
      }
      return post;
    }).sort((a, b) => {
      const dateA = a.post_timestamp || new Date(a.updated_at || a.created_at || 0).getTime();
      const dateB = b.post_timestamp || new Date(b.updated_at || b.created_at || 0).getTime();
      return dateB - dateA;
    });
    setLocalAdminCache('posts', nextPosts);
  }

  clearCache();
};

export const deletePost = async (id: string) => {
  try {
    const docSnap = await getDoc(doc(db, 'posts', id));
    const chunkCount = docSnap.exists() ? (docSnap.data().chunk_count || 0) : 0;
    
    if (chunkCount > 0) {
      let currentBatch = writeBatch(db);
      let writesInBatch = 0;
      for (let i = 0; i < chunkCount; i++) {
        currentBatch.delete(doc(db, 'posts', `${id}_chunk_${i}`));
        writesInBatch++;
        if (writesInBatch >= 400) {
          await currentBatch.commit();
          currentBatch = writeBatch(db);
          writesInBatch = 0;
        }
      }
      if (writesInBatch > 0) {
        await currentBatch.commit();
      }
    }
    
    // Fallback: silently try to delete subcollection chunks if they exist (unlikely due to permissions)
    try {
      const chunksRef = collection(db, `posts/${id}/chunks`);
      const chunksSnap = await getDocs(chunksRef);
      if (!chunksSnap.empty) {
        let currentBatch = writeBatch(db);
        let writesInBatch = 0;
        for (const d of chunksSnap.docs) {
          currentBatch.delete(d.ref);
          writesInBatch++;
          if (writesInBatch >= 400) {
            await currentBatch.commit();
            currentBatch = writeBatch(db);
            writesInBatch = 0;
          }
        }
        if (writesInBatch > 0) await currentBatch.commit();
      }
    } catch (e) { /* ignore fallback errors */ }

    await deleteDoc(doc(db, 'posts', id));

    // Update posts cache
    const cached = getLocalAdminCache<any[]>('posts');
    if (cached) {
      setLocalAdminCache('posts', cached.filter(p => p.id !== id));
    }

    clearCache();
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `posts/${id}`);
  }
};

// ============ SITE SETTINGS ============
export const getSiteSettings = async () => {
  const cached = getLocalAdminCache<Record<string, any>>('site_settings');
  if (cached && Object.keys(cached).length > 0) {
    return cached;
  }
  try {
    const snap = await getDocs(collection(db, 'site_settings'));
    const settings: Record<string, any> = {};
    snap.docs.forEach(d => {
      const data = d.data();
      settings[data.key] = { id: d.id, key: data.key, value: data.value };
    });
    setLocalAdminCache('site_settings', settings);
    return settings;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, 'site_settings');
    return {};
  }
};

export const getSiteSettingsFlat = async () => {
  // Save read operations by getting from the cached settings
  const settings = await getSiteSettings();
  const flat: Record<string, string> = {};
  Object.keys(settings).forEach(k => {
    flat[k] = settings[k].value;
  });
  return flat;
};

export const updateSiteSetting = async (key: string, value: string, existingId?: string) => {
  let docId = existingId;
  if (existingId) {
    await updateDoc(doc(db, 'site_settings', existingId), { value, updated_at: serverTimestamp() });
  } else {
    const docRef = await addDoc(collection(db, 'site_settings'), { key, value, updated_at: serverTimestamp() });
    docId = docRef.id;
  }

  // Update settings cache
  const cached = getLocalAdminCache<Record<string, any>>('site_settings');
  if (cached) {
    const nextSettings = { ...cached };
    nextSettings[key] = { id: docId, key, value };
    setLocalAdminCache('site_settings', nextSettings);
  }

  clearCache();
};

export const getSiteLastUpdated = async (): Promise<number> => {
  try {
    const docRef = doc(db, 'site_settings', 'last_updated');
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      return docSnap.data().timestamp || 0;
    }
    return 0;
  } catch (error) {
    handleFirestoreError(error, OperationType.GET, 'site_settings/last_updated');
    return 0;
  }
};

export const updateSiteLastUpdated = async () => {
  const docRef = doc(db, 'site_settings', 'last_updated');
  await setDoc(docRef, { timestamp: Date.now() }, { merge: true });
};

/**
 * Super-resilient Database Restoration Engine
 * Takes 100% database snapshot and restores it back to Firebase with precise chunking, IDs, and settings
 */
export const restoreDatabaseBackup = async (
  data: {
    categories: any[];
    category_links: any[];
    tablet_items: any[];
    posts: any[];
    settings_flat: Record<string, string>;
  },
  onProgress?: (progress: string) => void
) => {
  const log = onProgress || console.log;
  const CHUNK_SIZE = 200000;

  try {
    // 1. Restore Categories
    log('Categories restore process started...');
    let batch = writeBatch(db);
    let count = 0;
    for (const cat of data.categories) {
      const { id, ...fields } = cat;
      const ref = doc(db, 'categories', id);
      batch.set(ref, {
        ...fields,
        updated_at: serverTimestamp()
      }, { merge: true });
      count++;
      if (count >= 400) {
        await batch.commit();
        batch = writeBatch(db);
        count = 0;
      }
    }
    if (count > 0) {
      await batch.commit();
    }
    log(`Successfully restored ${data.categories.length} Categories!`);

    // 2. Restore Category Links
    log('Category links restore process started...');
    batch = writeBatch(db);
    count = 0;
    for (const link of data.category_links) {
      const { id, ...fields } = link;
      const ref = doc(db, 'category_links', id);
      batch.set(ref, {
        ...fields,
        updated_at: serverTimestamp()
      }, { merge: true });
      count++;
      if (count >= 400) {
        await batch.commit();
        batch = writeBatch(db);
        count = 0;
      }
    }
    if (count > 0) {
      await batch.commit();
    }
    log(`Successfully restored ${data.category_links.length} Category Links!`);

    // 3. Restore Tablet Items
    log('Tablet items restore process started...');
    batch = writeBatch(db);
    count = 0;
    for (const item of data.tablet_items) {
      const { id, ...fields } = item;
      const ref = doc(db, 'tablet_items', id);
      batch.set(ref, {
        ...fields,
        updated_at: serverTimestamp()
      }, { merge: true });
      count++;
      if (count >= 400) {
        await batch.commit();
        batch = writeBatch(db);
        count = 0;
      }
    }
    if (count > 0) {
      await batch.commit();
    }
    log(`Successfully restored ${data.tablet_items.length} Tablet Items!`);

    // 4. Restore Site Settings
    log('Site settings restore process started...');
    batch = writeBatch(db);
    count = 0;
    for (const [key, value] of Object.entries(data.settings_flat)) {
      if (key === 'last_updated' || key === 'id') continue;
      const ref = doc(db, 'site_settings', key);
      batch.set(ref, {
        key,
        value,
        updated_at: serverTimestamp()
      }, { merge: true });
      count++;
      if (count >= 400) {
        await batch.commit();
        batch = writeBatch(db);
        count = 0;
      }
    }
    if (count > 0) {
      await batch.commit();
    }
    log('Successfully restored Site Settings!');

    // 5. Restore Posts (with chunking support!)
    log(`Restoring ${data.posts.length} Posts...`);
    let postIndex = 0;
    for (const post of data.posts) {
      postIndex++;
      log(`Restoring post [${postIndex}/${data.posts.length}]: "${post.name_of_post}"...`);
      
      const { id, tables_html, tables_html_hi, tables_html_compressed, tables_html_hi_compressed, ...postFields } = post;
      
      const html = (tables_html || '') as string;
      const html_hi = (tables_html_hi || '') as string;
      
      const isChunked = (html.length + html_hi.length) > CHUNK_SIZE;
      const chunkCount = isChunked ? Math.ceil(Math.max(html.length, html_hi.length) / CHUNK_SIZE) : 0;
      
      const postData = {
        ...postFields,
        tables_html: isChunked ? '' : html,
        tables_html_hi: isChunked ? '' : html_hi,
        is_chunked: isChunked,
        chunk_count: chunkCount,
        updated_at: serverTimestamp(),
      };
      
      await setDoc(doc(db, 'posts', id), postData);
      
      if (isChunked) {
        const maxLen = Math.max(html.length, html_hi.length);
        let chunkIndex = 0;
        let postBatch = writeBatch(db);
        let writesInPostBatch = 0;
        
        for (let i = 0; i < maxLen; i += CHUNK_SIZE) {
          if (writesInPostBatch >= 400) {
            await postBatch.commit();
            postBatch = writeBatch(db);
            writesInPostBatch = 0;
          }
          const chunkRef = doc(db, 'posts', `${id}_chunk_${chunkIndex}`);
          postBatch.set(chunkRef, {
            index: chunkIndex,
            html: html.substring(i, i + CHUNK_SIZE),
            html_hi: html_hi.substring(i, i + CHUNK_SIZE),
          });
          writesInPostBatch++;
          chunkIndex++;
        }
        
        if (writesInPostBatch > 0) {
          await postBatch.commit();
        }
      }
    }
    
    log(`Successfully restored all ${data.posts.length} Posts!`);
    await updateSiteLastUpdated();
    
    // Clear Local Storage Administration Cache so UI updates instantly
    localStorage.removeItem('admin_db_cache_posts');
    localStorage.removeItem('admin_db_cache_categories');
    localStorage.removeItem('admin_db_cache_category_links');
    localStorage.removeItem('admin_db_cache_site_settings');
    clearLocalAdminCache('posts');
    clearLocalAdminCache('categories');
    clearLocalAdminCache('category_links');
    clearLocalAdminCache('site_settings');
    clearCache();
    log('Database recovery completed completely!');
    return true;
  } catch (error: any) {
    console.error('Failed to restore database backup:', error);
    log(`Error during restore: ${error.message || String(error)}`);
    throw error;
  }
};

// Removed realtime listeners
